config/routes.rb
Yagichannel::Application.routes.draw do
  get "login/index"

  resources :posts do
    resources :comments
  end

  match '/auth/:provider/callback' => 'sessions#callback'
  match "/logout" => "sessions#destroy", :as => :logout

  root :to => 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  attr_accessible :body, :user_id
  
  validates :body, :presence => true,
                       :length => { :minimum => 5 }
end

app/models/post.rb
class Post < ActiveRecord::Base
	
  attr_accessible :content, :title, :picture, :user_id
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  has_many :comments
  belongs_to :user

  validates :title, :presence => true
  validates :content, :presence => true,
                       :length => { :minimum => 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.screen_name = auth["info"]["nickname"]
      user.image = auth["info"]["image"]
    end
  end
end

app/controllers/application_controller.rb
# -*- encoding: utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery

  def login_required
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      redirect_to root_path
    end
  end

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
# -*- encoding: utf-8 -*-
class CommentsController < ApplicationController
  
  def create
    @post = Post.find(params[:post_id])
    @comment = Post.find(params[:post_id]).comments.create(params[:comment])
    if @comment.save
      redirect_to post_path(@post)
    else
      render :template => "posts/show"
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to :back
    end
  end
  
end

app/controllers/login_controller.rb
# -*- encoding: utf-8 -*-
class LoginController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
# -*- encoding: utf-8 -*-
class PostsController < ApplicationController
  #GET /posts
  #GET /posts.xml
  def index
    @posts = Post.all(:order => "created_at DESC")
    @users = User.all(:order => "created_at DESC")
    
    respond_to do |format|
      format.xml {render xml: @posts}
      format.xml {render xml: @users}
    end
  end
  
  def show
    @post = Post.find(params[:id])
    @comment = Post.find(params[:id]).comments.build
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(params[:post])
    if @post.save
      redirect_to posts_path, notice: '作成されました!'
    else
      render action: 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to posts_path, notice: '更新されました！'
    else
      render action: 'edit'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_url
  end
  
end

app/controllers/sessions_controller.rb
# -*- encoding: utf-8 -*-
class SessionsController < ApplicationController
  def callback
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path, :notice => "ログインしました！"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "ログアウトしました！"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "やぎちゃんねる" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "やぎちゃんねる", posts_path, :class => 'brand'%>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><% if current_user %>
                <p class="text-info"><%= current_user.name %>さん</p> <%= link_to "ログアウト" ,logout_path %>
              <% else %>
                  <%= link_to "Twitterでlogin","/auth/twitter" %>
              <% end %></li>
              <!-- <li><%= link_to "ログイン", "/auth/twitter" %></li> -->
              <!-- <li><%= link_to "Link3", "/path3"  %></li> -->

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">

        <div class="span12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Copyright © 2013 yaginuuu All Rights Reserved.</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/login/index.html.erb
<% if current_user %>
  Welcome <%= current_user.name %>!
  <%= link_to "Sign Out", signout_path %>
<% else %>
  <%= link_to "Sign in with Twitter", "/auth/twitter" %>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => {:multipart => true}) do |f| %>
<% if @post.errors.any? %>
<ul>
	<% @post.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<div class="field">
	<%= f.label :タイトル %>
	<%= f.text_field :title %>
</div>

<div class="field">
	<%= f.label :文 %>
	<%= f.text_area :content, :rows => 5 %>
</div>

<div class="field">
	<%= f.label :写真 %><br />
	<%= f.file_field :picture %>
</div>

	<%= f.hidden_field :user_id, :value => current_user.id %>

<div class="actions">
	<%= f.submit "投稿", :class => 'btn btn-primary'%>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div id="notice"><%= notice %></div>
<h1></h1>

<ul>
	<% @posts.each do |post| %>
	<li id="post_<%= post.id %>">
		<%= link_to post.title, post_path(post) %> by  <%= post.user.screen_name %> (<%= post.comments.size %>)
		<%= link_to '編集', edit_post_path(post) %>
		<%= link_to '削除', post, :confirm => '本当によろしいですか？', :method => :delete %>
	</li>
	<% end %>
</ul>	

<%= link_to '記事を投稿', new_post_path %>

<script>
	$(function(){
		setTimeout(function () {
		  $('#notice').fadeOut("slow")
		}, 800);
		
	});
</script>

app/views/posts/new.html.erb
<h1>記事を投稿</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %> <%= image_tag @post.user.image %> </h1> 

<p>
  <%= image_tag @post.picture(:medium), :class => "img-circle" if @post.picture.present? %>
</p>

<p><%= @post.content %></p>  

<h2>コメント</h2>
<ul>
	<% if @post.comments.any? %>
		<% @post.comments.each do |comment| %>
		<li id="comment_<%= comment.id %>">
			<%= comment.body %> (by <%= comment.user.screen_name %>)
			<%= link_to '削除', [comment.post, comment], :confirm => '本当に消しますか？',
														   :method => :delete%>
		</li>
		<% end %>
	<% else %>
		<li>まだコメントはありません</li>
	<% end %>
</ul>

<%= form_for([@post, @comment]) do |f| %>

<% if @comment.errors.any? %>
	<ul>
		<% @comment.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<div class="well">
	

	<div class="field">
		<%= f.label :コメント %>
		<%= f.text_area :body, :rows => 5 %>
	</div>

	<%= f.hidden_field :user_id, :value => current_user.id %>

	<div class="actions">
		<%= f.submit "送信", :class => "btn btn-primary" %>
	</div>

	<% end %>
</div>


<script>
	$(function(){
		$('a[data-method="delete"]').live('ajax:success', function(e, data, status, xhr) {
			$('#comment_'+data.comment.id).fadeOut("slow");
		});
		
	});
</script>